<!--
/**
 * Copyright © Funky Squid Labs Ltd. All rights reserved.
 * See COPYING.txt for license details.
 */
-->
<div class="module-info-section">
    <div class="module-header">
        <h1>Show &amp; Hide extra content with button.</h1>
        <img alt="Funky Squid Labs" src="<?php echo $this->getViewFileUrl('FunkySquid_Backend::css/images/new-logo.svg'); ?>" width="300px" height="" />
    </div>
    <div class="module-content">
        <p>With this module you are able to have a content section with a hidden content block which is visible once the link/button is clicked.</p>
        <p>The idea is that you do not have loads of content showing but enables you to have SEO rich content in place, this is really helpful on category landing pages.</p>
        <h2>Module usage</h2>
        <h3>Visible content.</h3>
        <p>This is the content section for the visible content area, add in your content into the WYSIWYG area and this displays as normal text/content.</p>
        <h3>Hidden content.</h3>
        <p>This section if for adding the content which is only displayed when the button/link are clicked or tapped.</p>
        <h3>Show/Hide link.</h3>
        <p>This section allows you to choose what you what the link/button displays when open and closed.</p>
        <ul>
            <li><b>Visible link text:</b> Place the text for when the text is hidden and to show that the link will show more.
                <ul>
                    <li>e.g. <b>Show or Open</b></li>
                </ul>
            </li>
            <li><b>Hidden link text:</b> Place your text for when the text is displayed and to show that the link will hide the extra content.
                <ul>
                    <li>e.g. <b>Hide or Close</b></li>
                </ul>
            </li>
        </ul>
        <h3>Button type.</h3>
        <p>This area is to select if you would like one of the following button types, please note that the button styles are inherited from the base page builder styles.</p>
        <ul>
            <li><b>Primary</b>: This is usually with a blue background &amp; white text.</li>
            <li><b>Secondary</b>: This is usually with a grey background &amp; black text.</li>
            <li><b>Text Link</b>: This is usually just text with an underline.</li>
        </ul>
    </div>
</div>
